### ISSUE TITLE
Enhancement: display CPU & memory usage

### ISSUE THREAD

**Issue by ciehanski** [dracula/tmux#36]
### Describe the feature you'd like
It'd be nice to have dracula tmux include the option to enable the display of CPU & memory usage meters within the statusline similar to [tmux-mem-cpu-load](https://github.com/thewtex/tmux-mem-cpu-load).

### Describe risks you've considered
I'm really unsure.

### Describe alternatives you've considered
I've tried installing [tmux-mem-cpu-load](https://github.com/thewtex/tmux-mem-cpu-load), but because I am using dracula theme, it will not display.

**Comment by ethancedwards8** [comment]
I'm taking a crack at it.

**Comment by ethancedwards8** [comment]
I solved it and made a PR :)

**Comment by ciehanski** [comment]
@ethancedwards8 wow, amazing work!! I really appreciate it, this will be incredibly useful.

**Comment by ethancedwards8** [comment]
I just added RAM percentage support!

**Comment by backpropper** [comment]
I'm aware of the above repository but the functionalities I mentioned above have not been implemented correctly in any plugin. The closest it comes to is the [https://github.com/tmux-plugins/tmux-cpu](https://github.com/tmux-plugins/tmux-cpu) repo which does not handle this. 

Nonetheless, this kind of functionality is super useful for thousands of developers who use remote GPU servers such as in AWS, GCP Azure, etc. Hence having this added functionality in addition to the existing CPU/RAM usage tool would make it a powerful plugin. I know many people migrated to the Dracula theme not only because of the looks but also because of the current functionality of CPU usage is seamlessly integrated into the theme.

**Comment by ethancedwards8** [comment]
I still have the code for the GPU module, I can start working working on it again. I had just stopped because @danerwilliams said we need a way to implement it a different way. But I do have that code.

**Comment by danerwilliams** [comment]
@backpropper @ethancedwards8 I’m in favor of trying to bring that functionality then. 

Really appreciate your feedback.

**Comment by ethancedwards8** [comment]
So keep working on the code? Or not? I'm caught up in some work for my internship, so I can't work on the custom listing, but I can try finish up the GPU, and the RAM modules.

**Comment by danerwilliams** [comment]
It sounds like there is a significant demand for the functionality @backpropper mentioned, so I would plan on merging that feature if you finished it. 

You should probably open a new issue for it since it’s a bit different than RAM/CPU.

**Comment by ethancedwards8** [comment]
Okay, will do.
